[package]
name = "hyperclient"
version = "0.1.8"
edition = "2021"
description = "A simple CLI application for sending cross-chain requests through Hyperbridge"
repository = "https://github.com/polytope-labs/hyperbridge"
authors = ["Polytope Labs <hello@polytope.technology>"]
tap = "polytope-labs/hyperclient"
publish-jobs = ["homebrew"]

[package.metadata.wix]
upgrade-guid = "3007F247-E2C4-4178-BD25-15526289376B"
path-guid = "6B08DE61-C026-4903-B3BF-9DAE0AB5CFF3"

[dependencies]
indicatif = "0.17.7"
clap = { version = "4.3.5", features = ["derive"] }
ethers = { version = "2.0.9", features = ["ws"] }
tokio = { version = "1.32.0", features = ["macros", "sync", "rt-multi-thread"] }
anyhow = "1.0.75"
sp-core = { version = "21.0.0", features = ["full_crypto"] }
hex = "0.4.3"
futures = "0.3.28"
jsonrpsee = { version = "0.20.2", features = ["ws-client"]}
log = "0.4.19"
env_logger = "0.10.0"
hex-literal = "0.4.1"
subxt = { version = "0.30.1", features = ["substrate-compat"] }
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }

ismp = { path = "../parachain/modules/ismp/core" }
debounced = { git= "https://github.com/polytope-labs/debounced", branch = "main"}
