[package]
name = "sync-committee-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]


[dependencies]
base2 = { version = "0.3.1", default-features=false}
ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", branch="dami/no-std-support" }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch="dami/seun-multi-proofs", default-features=false, features=["serde", "std"] }
hex-literal = { package = "hex-literal", version = "0.3.3" }
