[package]
name = "sync-committee-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]


[dependencies]
base2 = { version = "0.3.1", default-features = false}
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "ef89b4a4ef97cdd53a66ddb52e554667aca0beb2", default-features = false }
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "688a82389f60ed68c10404417c1f7f442ba748a1", default-features = false, features=["serde"] }
hex-literal = { package = "hex-literal", version = "0.3.3", default-features = false }

[features]
default = ["std"]
std = [
    "ssz-rs/std"
]
testing = []