[package]
name = "patricia-merkle-trie"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[dependencies]
trie-db = { version= "0.24.0", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
rlp = { version= "0.5.1", default-features = false }
parity-bytes = { version= "0.1.2", default-features = false }
ethereum-types = { version= "0.14.0", default-features = false }

hash256-std-hasher = { version = "0.15.2", optional = true }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", optional = true }

[dev-dependencies]
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
hex = "0.4.3"
hex-literal = "0.3.4"

[features]
default = []
std = [
    "sp-core",
    "hash256-std-hasher",
    "trie-db/std",
    "hash-db/std",
    "rlp/std",
    "parity-bytes/std",
    "ethereum-types/std",
]