[package]
name = "ethereum-beacon-light-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }


[workspace]
resolver = "2"
members = [
    "light-client-verifier",
    "light-client-primitives",
    "ics15-ethereum"
]
