[workspace]
resolver = "2"
members = [
    # Parachain
     "parachain/runtime",
     "parachain/node",

     "parachain/pallets/pallet-hyperspace/primitives",
     "parachain/pallets/pallet-hyperspace/simple-iavl",
     "parachain/pallets/pallet-hyperspace",
     "parachain/pallets/pallet-hyperspace-ping"
]

[patch."https://github.com/paritytech/jsonrpsee"]
jsonrpsee = { version = "0.16.2" }
