[workspace]
resolver = "2"
members = [
    "light-client-verifier",
    "light-client-primitives",
    "ics15-ethereum",
    "sync-committee-prover"
]

[patch."https://github.com/ralexstokes/ssz-rs"]
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "seun/ssz-merkle-multi-proof-phase-1"}
