[package]
name = "pallet-hyperspace"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.cargo-udeps.ignore]
normal = ["frame-benchmarking", "pallet-hyperspace-ping"]

[dependencies]
# crates.io
log = { version = "0.4.0", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.45", default-features = false }
sha2 = { version = "0.10.2", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["from", "display"]  }
# substrate
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.38", default-features = false }
cumulus-primitives-core  = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.38", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
# ibc
ibc-proto = { path = "../../../../ibc-rs/proto", default-features = false }
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", rev = "47e28b50d20138234f7a8b4254da71469f401714", default-features = false } # cannot be defined as optional in workspace
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "47e28b50d20138234f7a8b4254da71469f401714", default-features = false }
ics23 = { git = "https://github.com/confio/ics23", rev = "a4daeb4c24ce1be827829c0841446abc690c4f11", default-features = false }
hex = { version = "0.4.3", default-features = false }
# local deps
ibc-primitives = { path = "primitives", default-features = false }

# optional
hex-literal = { version = "0.3.4", default-features = false, optional = true }
prost = { version = "0.11", default-features = false, optional = true }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false, optional = true }
pallet-hyperspace-ping = { path = "../pallet-hyperspace-ping", default-features = false, optional = true }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false, optional = true }
serde = { version = "1.0", optional = true }

ibc-rs = {git = "ssh://git@github.com/polytope-labs/ibc-rs.git",  default-features = false}
ibc-derive = {git = "ssh://git@github.com/polytope-labs/ibc-rs.git", default-features = false}

codec = {package = "parity-scale-codec", version = "3.0.0", features = ["derive"], default-features = false}
tendermint-light-client-verifier={git = "https://github.com/informalsystems/tendermint-rs",rev = "47e28b50d20138234f7a8b4254da71469f401714",default-features = false}

[features]
default = ["std"]
std = [
    "codec/std",
    "log/std",
    "scale-info/std",
    "serde_json/std",
    "sha2/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-std/std",
    "sp-io/std",
    "sp-trie/std",
    "cumulus-primitives-core/std",
    "ibc-rs/std",
    "ibc-proto/std",
    "ibc-primitives/std",
    "parachain-info/std",
    "serde",
    "hex/std"
]

runtime-benchmarks = [
    "frame-benchmarking",
    "pallet-hyperspace-ping",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "hex-literal",
    "pallet-timestamp",
    "pallet-timestamp/runtime-benchmarks",
    "prost",
    "ibc-primitives/runtime-benchmarks",
]

try-runtime = ["frame-support/try-runtime"]
