[package]
name = "sync-committee-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]

[dependencies]
base2 = { version="0.2.2", default-features = false }
sync-committee-primitives = { path= "../primitives", default-features = false }
ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", rev = "c26206f18fcecbd69ca5d505ae4211a7bc756ad0", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", rev = "a78a600c7751527b74e038094ead04b697caa4a5", default-features = false, features=["serde"] }
milagro_bls = { git = "https://github.com/sigp/milagro_bls", default-features = false }
log = { version = "0.4.17", default-features = false }

[features]
default = ["std"]
std = [
    "ssz-rs/std",
    "milagro_bls/std",
    "log/std"
]
testing = ["sync-committee-primitives/testing"]
